name: Build and Deploy on Runner

on:
  push:
    branches:
      - main



env:
  IMAGE_NAME: babybala69/web-git-action-test:v1.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t babybala69/web-git-action-test:v1.0 .

      - name: Push Docker Image
        run: docker push babybala69/web-git-action-test:v1.0

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest


jobs:
  deploy:
    runs-on: self-hosted   # IMPORTANT

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.ITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/my-website:latest .

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/my-website:latest

      - name: Pull latest image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/my-website:latest

      - name: Stop old container
        run: |
          docker stop my-website || true
          docker rm my-website || true

      - name: Run new container
        run: |
          docker run -d \
            --name my-website \
            -p 1222:80 \
            --restart always \
            ghcr.io/${{ github.repository_owner }}/my-website:latest
