
name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: babybala69/14-18

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.VERSION }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Version Tag
        id: version
        run: |
          VERSION=$(date +'%Y.%m.%d')-${GITHUB_SHA::7}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Image
        run: |
          docker build -t $IMAGE_NAME:${{ steps.version.outputs.VERSION }} .
          docker tag $IMAGE_NAME:${{ steps.version.outputs.VERSION }} $IMAGE_NAME:latest

      - name: Push Image
        run: |
          docker push $IMAGE_NAME:${{ steps.version.outputs.VERSION }}
          docker push $IMAGE_NAME:latest

  deploy:
    needs: build
    runs-on: self-hosted
  

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Latest Image
        run: docker pull $IMAGE_NAME:latest

      - name: Stop and Remove Old Container
        run: |
          docker stop webapp || true
          docker rm webapp || true

      - name: Run New Container
        run: |
          docker run -d \
            --restart always \
            --name webapp \
            -p 80:80 \
            $IMAGE_NAME:latest
